/**:
  ros__parameters:
    controller_server: "compute_control_inputs"
    max_lin_vel: 2.0 # m/s
    max_ang_vel: 1.5 # rad/s

gpn_coordinator:
  ros__parameters:
    debug_stream: true
    odometry_topic: "odom"
    fish_cmd_topic: "fish_cmd"
    controller_timeout: 2 # sec (int)

gpn_pid_controller:
  ros__parameters:
    debug_stream: true
    pid_gain_lin_P: 1.0
    pid_gain_lin_I: 0.0
    pid_gain_lin_D: 0.1
    pid_gain_ang_P: 1.0
    pid_gain_ang_I: 0.0
    pid_gain_ang_D: 0.1          
    pid_D_term_max_time_threshold: 3.0 # sec
