/**:
  ros__parameters:
    pid_controller_server: "compute_pid_controls"

gpn_coordinator:
  ros__parameters:
    odometry_topic: "odom"
    fish_cmd_topic: "fish_cmd"    
    max_lin_vel: 2.0
    max_ang_vel: 1.5

gpn_pid_controller:
  ros__parameters:
    pid_controller_gain_P: 1.0
    pid_controller_gain_I: 0.0
    pid_controller_gain_D: 0.1     
