/**:
  ros__parameters:
    pid_controller_server: 'compute_pid_controls'
    max_lin_vel: 2.0
    max_ang_vel: 1.5

gpn_coordinator:
  ros__parameters:
    odometry_topic: 'odom'
    fish_cmd_topic: 'fish_cmd'   

gpn_pid_controller:
  ros__parameters:
    pid_controller_gain_lin_P: 1.0
    pid_controller_gain_lin_I: 0.0
    pid_controller_gain_lin_D: 0.1
    pid_controller_gain_ang_P: 1.0
    pid_controller_gain_ang_I: 0.0
    pid_controller_gain_ang_D: 0.1          
